### ISSUE TITLE
Fix the navbar styling on switching to reports

### ISSUE THREAD

**Issue by Elvismutinda** [IntelliSOFT-Consulting/pmi-kinga-malaria#10]

**Comment by nyatindopatrick** [comment]
- Adjust the height of the navbar to around 60px. 100px is too much
- Check on the font size. They look too big [(Comments here)](https://github.com/IntelliSOFT-Consulting/pmi-kinga-malaria/pull/8)
- Check on responsiveness
<img width="812" alt="Screenshot 2023-07-25 at 16 10 46" src="https://github.com/IntelliSOFT-Consulting/pmi-kinga-malaria/assets/48393059/0fb2ff5a-956a-45db-9480-78e7b435c3d4">
<img width="1175" alt="Screenshot 2023-07-25 at 16 15 42" src="https://github.com/IntelliSOFT-Consulting/pmi-kinga-malaria/assets/48393059/c15db8bd-8cae-4779-9e64-1d5c7288bc8f">
